<?php
/**
 * @file
 * Code for the global clf3 feature.
 */

include_once('wetkit_slider.features.inc');


/**
* Implements hook_install().
*/
function wetkit_slider_install() {
  
}

/**
* Implements hook_uninstall().
*/
function wetkit_slider_uninstall() {

}

/**
* Implements hook_page_alter().
*/
function wetkit_slider_page_alter(&$page) {

}

/**
* Implements hook_enable().
*/
function wetkit_slider_init(){
  
  //Temporary If Statement to run commands below one time
  if (variable_get('views_slider', 1) == 1) {
        
    
    
    
  }
  variable_set('views_slider', 0);
}

