<?php
/**
 * @file
 * Code for the wetkit_slider feature.
 */

include_once('wetkit_slider.features.inc');


/**
* Implements hook_install().
*/
function wetkit_slider_install() {
   
}

/**
* Implements hook_uninstall().
*/
function wetkit_slider_uninstall() {
  variable_del('views_slider');
}

/**
* Implements hook_load().
*/
function wetkit_slider_init(){
  //Set Flag
  if (variable_get('views_slider', 1) == 1) {
    drupal_flush_all_caches();
    // Create managed File object and associate with file field.
    $file1 = _add_file('parliamenthill_official.png', drupal_get_path('theme', 'genesis_clf') . '/images/parliamenthill.png');
    $file2 = _add_file('canada_official.png', drupal_get_path('theme', 'genesis_clf') . '/images/canada.png');

    // Slider Content
    $field_text_1_en = '<div class="tabs-content-pad">
      <p>Take Note: <a href="http://news.gc.ca">Recent National News</a><br />
        Learn more about the <a href="http://canada.gc.ca">Government of Canada</a></p>
    </div>';
    $field_text_1_fr = '<div class="tabs-content-pad">
      <p>Prenez note: <a href="http://news.gc.ca">Dernières Nouvelles nationales</a><br />
       En savoir plus sur le <a href="http://canada.gc.ca">Gouvernement du Canada</a></p>
    </div>';

    //Create Slider English
    $node = new stdClass();
    $node->type = 'main_slider';
    node_object_prepare($node);
    $node->title = 'Front Page Slider Official 1';
    $node->language = 'en';
    $node->status = 1;
    $node->uid = 1;
    $node->tnid = 3;
    $node->field_slider_title['und'][0]['value'] = 'First Slide Title';
    $node->field_slider_photo['und'][0] = (array)$file1;
    $node->field_slider_description['und'][0]['value'] = $field_text_1_en;
    $node->field_slider_description['und'][0]['format'] = 'full_html';
    $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_en;
    node_save($node); 

    //Create Slider French
    $node = new stdClass();
    $node->type = 'main_slider';
    node_object_prepare($node);
    $node->title = 'Première page diaporama officiel 1';
    $node->language = 'fr';
    $node->status = 1;
    $node->uid = 1;
    $node->tnid = 3;
    $node->field_slider_title['und'][0]['value'] = 'Titre première diaporama';
    $node->field_slider_photo['und'][0] = (array)$file1;
    $node->field_slider_description['und'][0]['value'] = $field_text_1_fr;
    $node->field_slider_description['und'][0]['format'] = 'full_html';
    $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_fr;
    node_save($node);
    
    //Create Slider English
    $node = new stdClass();
    $node->type = 'main_slider';
    node_object_prepare($node);
    $node->title = 'Front Page Slider Official 2';
    $node->language = 'en';
    $node->status = 1;
    $node->uid = 1;
    $node->tnid = 4;
    $node->field_slider_title['und'][0]['value'] = 'Second Slide Title';
    $node->field_slider_photo['und'][0] = (array)$file2;
    $node->field_slider_description['und'][0]['value'] = $field_text_1_en;
    $node->field_slider_description['und'][0]['format'] = 'full_html';
    $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_en;
    node_save($node); 

    //Create Slider French
    $node = new stdClass();
    $node->type = 'main_slider';
    node_object_prepare($node);
    $node->title = 'Première page diaporama officiel 2';
    $node->language = 'fr';
    $node->status = 1;
    $node->uid = 1;
    $node->tnid = 4;
    $node->field_slider_title['und'][0]['value'] = 'Titre dieuxème diaporama';
    $node->field_slider_photo['und'][0] = (array)$file2;
    $node->field_slider_description['und'][0]['value'] = $field_text_1_fr;
    $node->field_slider_description['und'][0]['format'] = 'full_html';
    $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_fr;
    node_save($node);   
    
    variable_set('views_slider', 0);
  }
}

/**
* Implements _add_file().
*/
function _add_file($filename, $filepath) {
  $file = new StdClass();
  $file->uid = 6;
  $file->uri = $filepath;
  $file->filename = $filename;
  $file->filemime = file_get_mimetype($file->uri);
  $file->status = 1;      
  $dest = file_default_scheme() . '://'.$filename; // Subdirectory name within files directory. ($dest is optional.)
  $file = file_copy($file, $dest);
  $file->display = 1;
  $file->description = ""; 
  return $file;
}