<?php
/**
 * @file
 * Code for the gov_web_usability feature.
 */

include_once('gov_web_usability.features.inc');

/**
* Implements hook_install().
*/
function gov_web_usability_install() {
  //Mega Menu EN
  $menu_depth1 = _add_custom_menu('<front>', 'Home', NULL, 'main-menu', 0, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);
  $menu_depth1 = _add_custom_menu('<front>', 'Help', NULL,'main-menu', 1, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);  
  _add_custom_menu('<front>', 'Contact Us', NULL, 'main-menu', 2,'en');
  _add_custom_menu('search', 'Search', NULL, 'main-menu', 3, 'en');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'en');  
  
  //Mega Menu FR
  $menu_depth1 = _add_custom_menu('<front>', 'Accueil', NULL, 'main-menu', 0, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3);
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3);  
  $menu_depth1 = _add_custom_menu('<front>', 'Aide', NULL, 'main-menu', 1, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3); 
  _add_custom_menu('<front>', 'Nous Contacter', NULL, 'main-menu', 2, 'fr');
  _add_custom_menu('search', 'Recherche', NULL, 'main-menu', 3, 'fr');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'fr');
  
  /* Add Menu Items to Gov Nav Bar */
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL,'menu-wet-header', 0, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Services', NULL, 'menu-wet-header', 1, 'en');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-eng.html', 'Departments', NULL, 'menu-wet-header', 2, 'en');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-header', 0, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Services', NULL, 'menu-wet-header', 1, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-fra.html', 'Ministères', NULL, 'menu-wet-header', 2, 'fr');
  
  /* Add Menu Items to Gov Footer Bar */
  _add_custom_menu('http://healthycanadians.gc.ca/index-eng.php', 'Health', 'healthycanadians.gc.ca', 'menu-wet-footer', 0, 'en');
  _add_custom_menu('http://www.voyage.gc.ca/index-eng.asp', 'Travel', 'travel.gc.ca', 'menu-wet-footer', 1, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'en');
  _add_custom_menu('http://www.jobbank.gc.ca/intro-eng.aspx', 'Jobs', 'jobbank.gc.ca', 'menu-wet-footer', 3, 'en');
  _add_custom_menu('http://actionplan.gc.ca/eng/index.asp', 'Economy', 'actionplan.gc.ca', 'menu-wet-footer', 4, 'en');
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'en');
  _add_custom_menu('http://canadiensensante.gc.ca/index-fra.php', 'Santé', 'canadiensensante.gc.ca', 'menu-wet-footer', 0, 'fr');
  _add_custom_menu('http://voyage.gc.ca/index-fra.asp', 'Voyage', 'voyage.gc.ca', 'menu-wet-footer', 1, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'fr');
  _add_custom_menu('http://www.guichetemplois.gc.ca/Intro-fra.aspx', 'Emplois', 'guichetemplois.gc.ca', 'menu-wet-footer', 3, 'fr');
  _add_custom_menu('http://www.plandaction.gc.ca/', 'Économie', 'plandaction.gc.ca', 'menu-wet-footer', 4, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'fr');
  
  /* Add Menu Items to Gov About Us Bar */
  _add_custom_menu('<front>', 'About Us', NULL, 'menu-wet-aboutus', 0, 'en');
  _add_custom_menu('<front>', 'Our Mandate', NULL, 'menu-wet-aboutus', 1, 'en');
  _add_custom_menu('<front>', 'Our Minister', NULL, 'menu-wet-aboutus', 2, 'en');
  _add_custom_menu('<front>', 'À propos de nous', NULL, 'menu-wet-aboutus', 0, 'fr');
  _add_custom_menu('<front>', 'Notre mandat', NULL, 'menu-wet-aboutus', 1, 'fr');
  _add_custom_menu('<front>', 'Le ministre', NULL, 'menu-wet-aboutus', 2, 'fr'); 
  
  /* Add Menu Items to Gov News Bar */
  _add_custom_menu('<front>', 'News', NULL, 'menu-wet-news', 0, 'en');
  _add_custom_menu('<front>', 'News Releases', NULL, 'menu-wet-news', 1, 'en');
  _add_custom_menu('<front>', 'Media Advisories', NULL, 'menu-wet-news', 2, 'en');
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-news', 3, 'en');
  _add_custom_menu('<front>', 'Média', NULL, 'menu-wet-news', 0, 'fr');
  _add_custom_menu('<front>', 'Communiqués', NULL, 'menu-wet-news', 1, 'fr');
  _add_custom_menu('<front>', 'Avis aux médias', NULL, 'menu-wet-news', 2, 'fr');
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-news', 3, 'fr');  
  
  /* Add Menu Items to Gov Contact Us Bar */
  _add_custom_menu('<front>', 'Contact Us', NULL, 'menu-wet-contactus', 0, 'en');
  _add_custom_menu('<front>', 'Phone Numbers', NULL, 'menu-wet-contactus', 1, 'en');
  _add_custom_menu('<front>', 'Find an Employee', NULL, 'menu-wet-contactus', 2, 'en');
  _add_custom_menu('<front>', 'Contactez-nous', NULL, 'menu-wet-contactus', 0, 'fr');
  _add_custom_menu('<front>', 'Numéros de téléphone', NULL, 'menu-wet-contactus', 1, 'fr');
  _add_custom_menu('<front>', 'Trouvez un(e) employé(e)', NULL, 'menu-wet-contactus', 2, 'fr'); 
  
  /* Add Menu Items to Gov Stay Connected Bar */
  _add_custom_menu('<front>', 'Stay Connected', NULL, 'menu-wet-stayconnected', 0, 'en');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-stayconnected', 1, 'en');
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-stayconnected', 2, 'en');
  _add_custom_menu('<front>', 'Feeds', NULL, 'menu-wet-stayconnected', 3, 'en');
  _add_custom_menu('<front>', 'Restez branchés', NULL, 'menu-wet-stayconnected', 0, 'fr');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-stayconnected', 1, 'fr');
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-stayconnected', 2, 'fr');
  _add_custom_menu('<front>', 'Fils de nouvelles', NULL, 'menu-wet-stayconnected', 3, 'fr');
  
  /* Add Menu Items to Gov Terms + Trans Bar */
  _add_custom_menu('<front>', 'Terms and Conditions', NULL, 'menu-wet-terms', 0, 'en');
  _add_custom_menu('<front>', 'Transparency', NULL, 'menu-wet-terms', 1, 'en');
  _add_custom_menu('<front>', 'Avis', NULL, 'menu-wet-terms', 0, 'fr');
  _add_custom_menu('<front>', 'Transparence', NULL, 'menu-wet-terms', 1, 'fr'); 
  
  //Clears all menu caches
  menu_cache_clear_all();
}

/**
* Implements hook_uninstall().
*/
function gov_web_usability_uninstall() {
  variable_del('views_temp');
}

/**
* Implements hook_page_alter().
*/
function gov_web_usability_page_alter(&$page) {
  //Hides the toolbar for administrator users if enabled
  if (module_exists('toolbar')) {
    global $user;
    if (in_array("administrator", $user->roles)) {
      unset($page['page_top']['toolbar']);
    }
  }
}

/**
* Implements hook_enable().
*/
function gov_web_usability_init(){
  //Set Flag
  if (variable_get('views_temp', 1) == 1) {      
    drupal_set_message(t('Please proceed to the !features section to run the Wizard or Custom setup.', array('!features' => l(t('FEATURES'), 'admin/structure/features'))), 'status');
    drupal_set_message(t('Please read the provided !documentation.', array('!documentation' => l(t('DOCUMENTATION'), 'documentation/styleguide/css-e'))), 'warning');
  
    variable_set('views_temp', 0);
  }
}

/* HELPER FUNCTIONS */

/**
* Implements _add_custom_menu().
*/
function _add_custom_menu($link, $title, $desc, $menu, $weight, $language, $mlid = 0, $plid = 0) {
  $options = array();
  if ($desc != NULL)
  {
    $options += array(
      'attributes' => array(
        'title' => $desc,
      ), 
    );
  }
  $item = array(
    'link_path' => $link,
    'link_title' => $title,
    'menu_name' => $menu,
    'weight' => $weight,
    'language' => $language,
    'customized' => 1,
    'options' => $options,
    'mlid' => $mlid,
    'plid' => $plid,
  );
  return menu_link_save($item);
}