<?php
/**
 * @file
 * Code for the gov_web_usability feature.
 */

include_once('gov_web_usability.features.inc');
include_once('gov_web_usability.blocks.inc');

/**
* Implements hook_install().
*/
function gov_web_usability_install() {
  //Mega Menu Depth Example EN
  $menu_depth1 = _add_custom_menu('<front>', 'Home', NULL, 'main-menu', 0, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);
  //Mega Menu Depth Example EN
  $menu_depth1 = _add_custom_menu('<front>', 'Help', NULL,'main-menu', 1, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth3);  
  //Remaining Links EN
  _add_custom_menu('<front>', 'Contact Us', NULL, 'main-menu', 2,'en');
  _add_custom_menu('search', 'Search', NULL, 'main-menu', 3, 'en');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'en');  
  
  //Mega Menu Depth Example FR
  $menu_depth1 = _add_custom_menu('<front>', 'Accueil', NULL, 'main-menu', 0, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3);
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3);  
  //Mega Menu Depth Example FR
  $menu_depth1 = _add_custom_menu('<front>', 'Aide', NULL, 'main-menu', 1, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'menu-col', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  $menu_depth3 = _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth3); 
  //Remaining Links FR
  _add_custom_menu('<front>', 'Nous Contacter', NULL, 'main-menu', 2, 'fr');
  _add_custom_menu('search', 'Recherche', NULL, 'main-menu', 3, 'fr');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'fr');
  
  /* Add Menu Items to Gov Nav Bar */
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL,'menu-wet-header', 0, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Services', NULL, 'menu-wet-header', 1, 'en');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-eng.html', 'Departments', NULL, 'menu-wet-header', 2, 'en');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-header', 0, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Services', NULL, 'menu-wet-header', 1, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-fra.html', 'Ministères', NULL, 'menu-wet-header', 2, 'fr');
  
  /* Add Menu Items to Gov Footer Bar */
  _add_custom_menu('http://healthycanadians.gc.ca/index-eng.php', 'Health', 'healthycanadians.gc.ca', 'menu-wet-footer', 0, 'en');
  _add_custom_menu('http://www.voyage.gc.ca/index-eng.asp', 'Travel', 'travel.gc.ca', 'menu-wet-footer', 1, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'en');
  _add_custom_menu('http://www.jobbank.gc.ca/intro-eng.aspx', 'Jobs', 'jobbank.gc.ca', 'menu-wet-footer', 3, 'en');
  _add_custom_menu('http://actionplan.gc.ca/eng/index.asp', 'Economy', 'actionplan.gc.ca', 'menu-wet-footer', 4, 'en');
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'en');
  _add_custom_menu('http://canadiensensante.gc.ca/index-fra.php', 'Santé', 'canadiensensante.gc.ca', 'menu-wet-footer', 0, 'fr');
  _add_custom_menu('http://voyage.gc.ca/index-fra.asp', 'Voyage', 'voyage.gc.ca', 'menu-wet-footer', 1, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'fr');
  _add_custom_menu('http://www.guichetemplois.gc.ca/Intro-fra.aspx', 'Emplois', 'guichetemplois.gc.ca', 'menu-wet-footer', 3, 'fr');
  _add_custom_menu('http://www.plandaction.gc.ca/', 'Économie', 'plandaction.gc.ca', 'menu-wet-footer', 4, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'fr');
  
  /* Add Menu Items to Gov About Us Bar */
  _add_custom_menu('<front>', 'About Us', NULL, 'menu-wet-aboutus', 0, 'en');
  _add_custom_menu('<front>', 'Our Mandate', NULL, 'menu-wet-aboutus', 1, 'en');
  _add_custom_menu('<front>', 'Our Minister', NULL, 'menu-wet-aboutus', 2, 'en');
  _add_custom_menu('<front>', 'À propos de nous', NULL, 'menu-wet-aboutus', 0, 'fr');
  _add_custom_menu('<front>', 'Notre mandat', NULL, 'menu-wet-aboutus', 1, 'fr');
  _add_custom_menu('<front>', 'Le ministre', NULL, 'menu-wet-aboutus', 2, 'fr'); 
  
  /* Add Menu Items to Gov News Bar */
  _add_custom_menu('<front>', 'News', NULL, 'menu-wet-news', 0, 'en');
  _add_custom_menu('<front>', 'News Releases', NULL, 'menu-wet-news', 1, 'en');
  _add_custom_menu('<front>', 'Media Advisories', NULL, 'menu-wet-news', 2, 'en');
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-news', 3, 'en');
  _add_custom_menu('<front>', 'Média', NULL, 'menu-wet-news', 0, 'fr');
  _add_custom_menu('<front>', 'Communiqués', NULL, 'menu-wet-news', 1, 'fr');
  _add_custom_menu('<front>', 'Avis aux médias', NULL, 'menu-wet-news', 2, 'fr');
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-news', 3, 'fr');  
  
  /* Add Menu Items to Gov Contact Us Bar */
  _add_custom_menu('<front>', 'Contact Us', NULL, 'menu-wet-contactus', 0, 'en');
  _add_custom_menu('<front>', 'Phone Numbers', NULL, 'menu-wet-contactus', 1, 'en');
  _add_custom_menu('<front>', 'Find an Employee', NULL, 'menu-wet-contactus', 2, 'en');
  _add_custom_menu('<front>', 'Contactez-nous', NULL, 'menu-wet-contactus', 0, 'fr');
  _add_custom_menu('<front>', 'Numéros de téléphone', NULL, 'menu-wet-contactus', 1, 'fr');
  _add_custom_menu('<front>', 'Trouvez un(e) employé(e)', NULL, 'menu-wet-contactus', 2, 'fr'); 
  
  /* Add Menu Items to Gov Stay Connected Bar */
  _add_custom_menu('<front>', 'Stay Connected', NULL, 'menu-wet-stayconnected', 0, 'en');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-stayconnected', 1, 'en');
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-stayconnected', 2, 'en');
  _add_custom_menu('<front>', 'Feeds', NULL, 'menu-wet-stayconnected', 3, 'en');
  _add_custom_menu('<front>', 'Restez branchés', NULL, 'menu-wet-stayconnected', 0, 'fr');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-stayconnected', 1, 'fr');
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-stayconnected', 2, 'fr');
  _add_custom_menu('<front>', 'Fils de nouvelles', NULL, 'menu-wet-stayconnected', 3, 'fr');
  
  /* Add Menu Items to Gov Terms + Trans Bar */
  _add_custom_menu('<front>', 'Terms and Conditions', NULL, 'menu-wet-terms', 0, 'en');
  _add_custom_menu('<front>', 'Transparency', NULL, 'menu-wet-terms', 1, 'en');
  _add_custom_menu('<front>', 'Avis', NULL, 'menu-wet-terms', 0, 'fr');
  _add_custom_menu('<front>', 'Transparence', NULL, 'menu-wet-terms', 1, 'fr'); 
  
  //Clears all menu caches
  menu_cache_clear_all();
  
  //Languages
  db_update('languages')
    ->fields(array(
      'prefix' => 'eng',
    ))
  ->condition('language', 'en')
  ->execute();

  db_update('languages')
    ->fields(array(
      'prefix' => 'fra',
    ))
  ->condition('language', 'fr')
  ->execute();

  //Multilingual Variables
  variable_set('i18n_variable_conf', array('site_name'));
  variable_set('i18n_variable_list', array('site_name'));
  i18n_variable_set('site_name', 'Toolkit Expérience Web', 'fr');

  //Clear all caches
  cache_clear_all('*', I18N_VARIABLE_CACHE, TRUE);
}

/**
* Implements hook_uninstall().
*/
function gov_web_usability_uninstall() {
  variable_del('views_temp');
}

/**
* Implements hook_page_alter().
*/
function gov_web_usability_page_alter(&$page) {
  //Hides the toolbar module from adminstrators
  global $user;
  if (in_array("administrator", $user->roles)) {
    unset($page['page_top']['toolbar']);
  }
}

/**
* Implements hook_enable().
*/
function gov_web_usability_init(){
  //Temporary Statement to run commands below one time
  if (variable_get('views_temp', 1) == 1) {
    //Update Certain Regions
    //db_query("UPDATE {block} SET region = 'headlines', status = '1' WHERE module = 'views' AND theme = 'genesis_clf' AND delta = 'headlines_front_page-block'"); 
    //db_query("UPDATE {block} SET region = 'headlines', status = '1' WHERE module = 'views' AND theme = 'genesis_clf_intranet' AND delta = 'headlines_front_page-block'");
    
    //Slider Additions
    if (module_exists('wetkit_slider'))
    {
      // Create managed File object and associate with file field.
      $file1 = _add_file('parliamenthill_official.png', drupal_get_path('theme', 'genesis_clf') . '/images/parliamenthill.png');
      $file2 = _add_file('canada_official.png', drupal_get_path('theme', 'genesis_clf') . '/images/canada.png');

      // Slider Content
      $field_text_1_en = '<div class="tabs-content-pad">
        <p>Take Note: <a href="http://news.gc.ca">Recent National News</a><br />
          Learn more about the <a href="http://canada.gc.ca">Government of Canada</a></p>
      </div>';

      $field_text_1_fr = '<div class="tabs-content-pad">
        <p>Prenez note: <a href="http://news.gc.ca">Dernières Nouvelles nationales</a><br />
         En savoir plus sur le <a href="http://canada.gc.ca">Gouvernement du Canada</a></p>
      </div>';

      //Create Slider English
      $node = new stdClass();
      $node->type = 'main_slider';
      node_object_prepare($node);
      $node->title = 'FrontPage Slider Official 1';
      $node->language = 'en';
      $node->status = 1;
      $node->uid = 1;
      $node->tnid = 3;
      $node->field_slider_title['und'][0]['value'] = 'First Slide Title';
      $node->field_slider_photo['und'][0] = (array)$file1;
      $node->field_slider_description['und'][0]['value'] = $field_text_1_en;
      $node->field_slider_description['und'][0]['format'] = 'full_html';
      $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_en;
      node_save($node); 
      
      $node = new stdClass();
      $node->type = 'main_slider';
      node_object_prepare($node);
      $node->title = 'FrontPage Slider Official 2';
      $node->language = 'en';
      $node->status = 1;
      $node->uid = 1;
      $node->tnid = 3;
      $node->field_slider_title['und'][0]['value'] = 'Second Slide Title';
      $node->field_slider_photo['und'][0] = (array)$file2;
      $node->field_slider_description['und'][0]['value'] = $field_text_1_en;
      $node->field_slider_description['und'][0]['format'] = 'full_html';
      $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_en;
      node_save($node); 

      //Create Slider French
      $node = new stdClass();
      $node->type = 'main_slider';
      node_object_prepare($node);
      $node->title = 'FrontPage Curseur officiel 1';
      $node->language = 'fr';
      $node->status = 1;
      $node->uid = 1;
      $node->tnid = 3;
      $node->field_slider_title['und'][0]['value'] = 'Titre Première diapositive';
      $node->field_slider_photo['und'][0] = (array)$file1;
      $node->field_slider_description['und'][0]['value'] = $field_text_1_fr;
      $node->field_slider_description['und'][0]['format'] = 'full_html';
      $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_fr;
      node_save($node);
      
      $node = new stdClass();
      $node->type = 'main_slider';
      node_object_prepare($node);
      $node->title = 'FrontPage Curseur officiel 2';
      $node->language = 'fr';
      $node->status = 1;
      $node->uid = 1;
      $node->tnid = 3;
      $node->field_slider_title['und'][0]['value'] = 'Titre Dieuxème diapositive';
      $node->field_slider_photo['und'][0] = (array)$file2;
      $node->field_slider_description['und'][0]['value'] = $field_text_1_fr;
      $node->field_slider_description['und'][0]['format'] = 'full_html';
      $node->field_slider_description['und'][0]['safe_value'] = $field_text_1_fr;
      node_save($node);
      
      //Add the slider block to region
      //db_query("UPDATE {block} SET region = 'slideshow', status = '1' WHERE module = 'views' AND theme = 'genesis_clf' AND delta = 'slider-block'"); 
    }
        
    //Add the Default Blocks
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'videos_blocks',
      'language' => 'en',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'priorities_blocks',
      'language' => 'en',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'minister_blocks',
      'language' => 'en',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'connected_blocks',
      'language' => 'en',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'videos_blocks2',
      'language' => 'fr',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'priorities_blocks_fr',
      'language' => 'fr',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'minister_blocks_fr',
      'language' => 'fr',
    ))->execute();
    
    db_insert('i18n_block_language')->fields(array(
      'module' => 'gov_web_usability',
      'delta' => 'connected_blocks_fr',
      'language' => 'fr',
    ))->execute();
    
    drupal_set_message(t('Please run migration scripts for default content from: !module.', array('!module' => l(t('wetkit_migrate'), 'admin/content/migrate'))), 'status');
    drupal_set_message(t('Please read the provided !documentation.', array('!documentation' => l(t('Documentation'), 'documentation/styleguide/css-e'))), 'warning');
  }
  variable_set('views_temp', 0);
}

/* HELPER FUNCTIONS */

/**
* Implements _add_custom_menu().
*/
function _add_custom_menu($link, $title, $desc, $menu, $weight, $language, $mlid = 0, $plid = 0) {
  $options = array();
  $options += array(
    'attributes' => array(
      'title' => $desc,
    ), 
  );
  $item = array(
    'link_path' => $link,
    'link_title' => $title,
    'menu_name' => $menu,
    'weight' => $weight,
    'language' => $language,
    'customized' => 1,
    'options' => $options,
    'mlid' => $mlid,
    'plid' => $plid,
  );
  return menu_link_save($item);
}

/**
* Implements _add_file().
*/
function _add_file($filename, $filepath) {
  $file = new StdClass();
  $file->uid = 6;
  $file->uri = $filepath;
  $file->filename = $filename;
  $file->filemime = file_get_mimetype($file->uri);
  $file->status = 1;      
  $dest = file_default_scheme() . '://'.$filename; // Subdirectory name within files directory. ($dest is optional.)
  $file = file_copy($file, $dest);
  $file->display = 1;
  $file->description = ""; 
  return $file;
}