<?php
/**
 * @file
 * Code for the wetkit_i18n feature.
 */

include_once('wetkit_i18n.features.inc');

/**
* Implements hook_install().
*/
function wetkit_i18n_install() {

}

/**
* Implements hook_uninstall().
*/
function wetkit_i18n_uninstall() {

}

/**
* Implements hook_language_init().
*/
function wetkit_i18n_language_init() {  
  //Set Flag
  if (variable_get('views_i18n', 1) == 1) { 
    
    //Take care of language + domain
     db_update('languages')
      ->fields(array(
        'prefix' => 'eng',
        'domain' => variable_get('radio_language_domain_en'),
      ))
    ->condition('language', 'en')
    ->execute();
        
    db_update('languages')
      ->fields(array(
        'prefix' => 'fra',
        'domain' => variable_get('radio_language_domain_fr'),
      ))
    ->condition('language', 'fr')
    ->execute();

    //Multilingual Variables
    i18n_variable_set('site_name', 'Toolkit Expérience Web', 'fr');

    //Clear all caches
    cache_clear_all('*', I18N_VARIABLE_CACHE, TRUE);

    variable_set('views_i18n', 0);
  }
}