<?php
/**
 * @file
 */

// Drupal needs this blank file.

function wetkit_post_install_install() {
    
  //variable_set('features_set', 1);
  
  //add some documentation to assist the end user
  //cache_clear_all();
  migrate_flush_caches();
  
  $migration = Migration::getInstance('XML_Web_Usability_Gov');
  $result = $migration->processImport();
  $migration = Migration::getInstance('HTML_Documentation');
  $result = $migration->processImport();

}

function wetkit_post_install_uninstall() {
  
  variable_del('features_set');
  
  //add some documentation to assist the end user
  $migration = Migration::getInstance('XML_Web_Usability_Gov');
  $result = $migration->processRollback();
  $migration = Migration::getInstance('XML_Documentation');
  $result = $migration->processRollback();
  cache_clear_all();
}

function wetkit_post_install_init() {
  if (variable_get('features_set', 1) == 1) {
    
    //Update Certain Regions
    //db_query("UPDATE {block} SET region = 'sidebar_first', status = '1' WHERE module = 'menu' AND theme = 'genesis_clf' AND delta = 'menu-documentation'"); 

    global $theme;
    db_query('UPDATE {block} SET region = :region, status = :status WHERE module = :module AND theme = :theme AND delta = :delta', 
         array( ':region' => 'sidebar_first', 
                ':status' => '1', 
                ':module' => 'menu',
                ':theme' => $theme,
                ':delta' => 'menu-documentation'));
    
    
    drupal_flush_all_caches();
    features_revert();
  }
  variable_set('features_set', 0);
}