<?php
/**
 * @file
 */

// Drupal needs this blank file.

function wetkit_post_install_install() {
  //add some documentation to assist the end user
  drupal_flush_all_caches();
  $migration = Migration::getInstance('XML_Web_Usability_Gov');
  $result = $migration->processImport();
  $migration = Migration::getInstance('HTML_Documentation');
  $result = $migration->processImport();
  
  //Update Certain Regions
  db_query("UPDATE {block} SET region = 'sidebar_first', status = '1' WHERE module = 'menu' AND theme = 'genesis_clf' AND delta = 'menu-documentation'"); 

  //revert some features that didn't work as expected during install
  //features_revert(array('wetkit_ckeditor' => array('ckeditor_profile')));
}

function wetkit_post_install_uninstall() {
  //add some documentation to assist the end user
  $migration = Migration::getInstance('XML_Web_Usability_Gov');
  $result = $migration->processRollback();
  $migration = Migration::getInstance('XML_Documentation');
  $result = $migration->processRollback();
  cache_clear_all();
}

